### ISSUE TITLE
MAC Address of eth0 is random on every boot

### ISSUE THREAD

**Issue by sat8** [rockchip-linux/meta-rockchip#11]
Hi

I have run in to an issue with MAC address of the ethernet port getting a random address on every boot.
While looking for possible solutions on the web, a post  on raspberry pi forums indicated that the mac address is linked to cpu serial and the CPU serial being null can be a reason for kernel to assign random mac address. 

On Tinkerboard, the output of command **cat /proc/cpuinfo** returns a null serial for cpus.

![image](https://cloud.githubusercontent.com/assets/8937796/25285753/39f7c960-26b3-11e7-99b4-89801ac2626b.png)

Please advise a solution.

**Comment by wzyy2** [comment]
Hi,

Tinker board usually read mac adress from i2c.
You can pick this patch to u-boot.
https://patchwork.ozlabs.org/patch/752938/

And if you update kernel to latest release-4.4, it will also use a fixed mac adress.

**Comment by sat8** [comment]
great. This has fixed it. many thanks.
