### ISSUE TITLE
build error - firmware-rk_git

### ISSUE THREAD

**Issue by sat8** [rockchip-linux/meta-rockchip#24]
Yocto build is failing for the recipe firmware-rk_git as there is no file such as test.mp4

SRC_URI = "git://github.com/rockchip-linux/rkbin.git \
	file://test.mp4"

Is this URL ought to be remote than local to the build PC?

thnx

**Comment by wzyy2** [comment]
sorry...I push my dev changes..

**Comment by wzyy2** [comment]
have remove it
