### ISSUE TITLE
Kernel panic booting "core-image-minimal"

### ISSUE THREAD

**Issue by pauldotknopf** [rockchip-linux/meta-rockchip#32]
```
Build Configuration:
BB_VERSION           = "1.36.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "evb-rk3328"
DISTRO               = "poky"
DISTRO_VERSION       = "2.4.2"
TUNE_FEATURES        = "aarch64"
TARGET_FPU           = ""
meta
meta-poky
meta-yocto-bsp       = "rocko:fdeecc901196bbccd7c5b1ea4268a2cf56764a62"
meta                 = "rocko:1b18cdf6b8bdb00ff5df165b9ac7bc2b10c87d57"
meta-oe              = "rocko:dacfa2b1920e285531bec55cd2f08743390aaf57"
meta-rockchip        = "rocko:eae0225c335b4e5822dd7c144d5ed6219045e7b7"
```

Here is my [image-gpt.img](https://drive.google.com/file/d/12-mT4wTUG9q4mm_uVO7TfVGIm6_aiYCl/view?usp=sharing) file if you want to try to boot it.

I don't have debug serial port or UART, so it is hard to get you a clean boot log, but I took some pictures. Maybe it helps. If not, I can try to hookup a boot debug port.

![boot1](https://user-images.githubusercontent.com/523150/38867427-07d5a350-4212-11e8-8568-7725ed48e4a9.jpg)
![boot2](https://user-images.githubusercontent.com/523150/38867428-07e22670-4212-11e8-93b1-73bf7c83af88.jpg)
![boot3](https://user-images.githubusercontent.com/523150/38867429-07f0902a-4212-11e8-96b2-34c30a2f2d1e.jpg)
![boot4](https://user-images.githubusercontent.com/523150/38867430-0801739a-4212-11e8-987b-f613e1365212.jpg)
![boot5](https://user-images.githubusercontent.com/523150/38867431-080ff2da-4212-11e8-92f0-f967c0caac48.jpg)

Here is a picture of my board (RK3328).

![board1](https://user-images.githubusercontent.com/523150/38867575-6510cc20-4212-11e8-9e40-7e461e64e55d.jpg)
![board2](https://user-images.githubusercontent.com/523150/38867576-651f3ca6-4212-11e8-9a52-2f561cf328db.jpg)

When I use the provided Etcher app and flash Debian, it boots fine. It must be something in the Yocto configuration.

**Comment by pauldotknopf** [comment]
Wrong repo?

**Comment by wzyy2** [comment]
You'd better give a complete log
