### ISSUE TITLE
How can I add my own custom device tree and kernel config?

### ISSUE THREAD

**Issue by weiqj** [rockchip-linux/meta-rockchip#33]
We have our own custom board and I would like to use Yocto to build it.
However I can't find information about add my custom device tree and kernel config.
Can anybody help?

**Comment by mirzak** [comment]
You probably should create your own BSP layer, https://www.yoctoproject.org/docs/current/bsp-guide/bsp-guide.html .

You can bbappend the rockchip recipes or create custom recipe for linux kernel that fetches from your source.
