### ISSUE TITLE
Support for NANOPC-T4

### ISSUE THREAD

**Issue by nandra** [rockchip-linux/meta-rockchip#48]
I plan to buy https://www.friendlyarm.com/index.php?route=product/product&product_id=225 but looking at machines seems not yet supported by this meta layer. Does anyone work on it already? Otherwise I can also contribute. Thanks.

**Comment by JeffyCN** [comment]
sorry, i'm not familiar(or be able to test) with this board.

adding support for new boards usually needs patches for kernel/u-boot(mostly config and dts), and a machine config(see examples under meta-rockchip/conf/machine)

**Comment by nandra** [comment]
@JeffyCN ok thanks for info.

**Comment by floion** [comment]
Hi, we have this https://github.com/balena-os/meta-nanopc-t4/tree/thud but we didn't update it a while though it should work
