### ISSUE TITLE
Resize SD card on first boot/ Use available free space

### ISSUE THREAD

**Issue by sat8** [rockchip-linux/meta-rockchip#5]
Hi 

This is just a feature request. 

After writing the Yocto image to SD card, it would be nice to have a resize script that can use the free space.  Another idea is to create a new partition right after writing the image. Presently, I am doing this manually to store my use apps and data in a new partition right after the ROOTFS.

Can you recommend a way to do this automatically?

**Comment by wzyy2** [comment]
https://github.com/rockchip-linux/meta-rockchip-extra/blob/morty/recipes-rk/autostart/resize2fs_0.1.bb

Include it in your image.
