### ISSUE TITLE
PX30 fails to boot with kernel 4.19

### ISSUE THREAD

**Issue by pbeTrifork** [rockchip-linux/meta-rockchip#51]
When trying to use the kernel 4.19 on the px30-evb the boot stops outputting data to uart0 after initializing the  Synopsys Designware Multimedia Card Interface Driver.

**Comment by JeffyCN** [comment]
that sounds like a bug related to BSP kernel 4.19, maybe try the newest version:
https://github.com/JeffyCN/mirrors/tree/kernel-4.19 

currently the yocto only tested 4.19 on rk356x boards.
