### ISSUE TITLE
/meta-python2/recipes-core/images/meta-python-ptest-image.bb:1: Could not include required file meta-python2-image-base.bb

### ISSUE THREAD

**Issue by code-wangshuyi** [rockchip-linux/meta-rockchip#52]

**Comment by code-wangshuyi** [comment]
/meta-python2/recipes-core/images/meta-python-ptest-image.bb:1: Could not include required file meta-python2-image-base.bb

**Comment by JeffyCN** [comment]
Looks like something wrong in the PC environment or the old official zeus meta-python2.

The newest SDK updated to gatesgarth, please retry it.

**Comment by JeffyCN** [comment]
Here're my manifests:
https://github.com/JeffyCN/yocto-manifests

For new host environments(e.g. ubuntu 20.04), please try dunfell for gatesgarth
