### ISSUE TITLE
Chromium v4l2 decoder does not initialize

### ISSUE THREAD

**Issue by MastaG** [rockchip-linux/meta-rockchip#54]
Hi there,

Since you guys seem to maintain the v4l linux patches.
I've rebased them on top of chromium 89.0.4389.114 except for 0007-ui-ozone-wayland-Rely-on-implicit-sync-when-eglCreat.patch which doesn't apply any longer.

See: https://github.com/MastaG/odroid-oe-core/tree/master/odroid-os/recipes-browser/chromium/files

But when I try to play some video, chromium will show me: [9318:9346:0409/131402.471009:ERROR:v4l2_video_decode_accelerator.cc(508)] could not create EGLImageKHR, index=9 texture_id=239

I'm running Chromium with --in-process-gpu.
See: 
[about-gpu.txt](https://github.com/rockchip-linux/meta-rockchip/files/6285445/about-gpu.txt)

Any ideas?

**Comment by JeffyCN** [comment]
Well, i don't think this error would related to v4l2.

It shows your EGL implement failed to import dma buf to eglimagekhr(could be not supported at all or just for the specific format or requires special EGL attrs).

Please try to confirm it which the GPU team and maybe write a simple test for this API(eglCreateImageKHR)
