### ISSUE TITLE
Difference to yocto upstream's meta-rockchip layer?

### ISSUE THREAD

**Issue by didrod** [rockchip-linux/meta-rockchip#56]
Hi. I see this repository is a fork of the [yocto's upstream meta-rockchip layer](https://git.yoctoproject.org/cgit/cgit.cgi/meta-rockchip/about/). seeing that the upstream is still being updated, I'm just confused which one should I choose to start off.

could you briefly explain me the difference to the upstream? what was the reason of the breakout?

**Comment by JeffyCN** [comment]
the upstream layer is mainly using upstream u-boot and kernel.
this layer is using Rockchip BSP u-boot and kernel(and also a lot of user space packages based on them).

**Comment by didrod** [comment]
quite obvious. thanks.
