### ISSUE TITLE
Tinkerboard SD-CARD

### ISSUE THREAD

**Issue by Ereaey** [rockchip-linux/meta-rockchip#57]
Hello,

I tried to make an image for a tinkerboard. (i used branch yocto-next)
I flashed the .wic on my SD card but nothing is booting.

Is the uboot intended to be put on an SD card? I flashed the .wic is this the right way ?

Thank you

**Comment by JeffyCN** [comment]
Booting on SD card is complicated :(

First of all, you need to make sure SD card works during booting stage. After that, Rockchip has an official tool for making a bootable SD card(from update.img). About all these, please ask Tinerboard FAE for support.

If that way works, flashing .wic directly should work too.
