### ISSUE TITLE
Compatibility with newer Yocto releases

### ISSUE THREAD

**Issue by floion** [rockchip-linux/meta-rockchip#67]
Hi,
I was looking to see if you support newer Yocto releases but I see the newest one is rocko. Do you plan to create a `honister` branch maybe for working with the Yocto Honister release?

**Comment by JeffyCN** [comment]
rocko is no longer supported for a long time.

for hardknott: https://github.com/JeffyCN/yocto-manifests/tree/hardknott-next

honister is still WIP, it has a different override syntax than older versions, i'm planning to switch to it the next month:
https://github.com/JeffyCN/meta-rockchip/tree/honister
https://github.com/JeffyCN/yocto-conf/tree/honister

**Comment by floion** [comment]
Hi, thanks for your reply. I looked in the layer.conf and saw that the approach you take is to use one branch that supports multiple Yocto releases. Are you taking into account creating branches of https://github.com/rockchip-linux/meta-rockchip/ for each Yocto release instead?

**Comment by JeffyCN** [comment]
i'm planning to do it, but begin with honister

**Comment by floion** [comment]
Great, thanks!

**Comment by JeffyCN** [comment]
done

**Comment by floion** [comment]
Thanks!

**Comment by floion** [comment]
But I still do not see a Honister branch

**Comment by JeffyCN** [comment]
> Thanks!

due to company policy, this github account(rockchip-linux) is no longer maintained.
check the newest version in:
https://github.com/JeffyCN/yocto-manifests/branches
