### ISSUE TITLE
Hardknott mesa

### ISSUE THREAD

**Issue by shawn-pfister** [rockchip-linux/meta-rockchip#70]
Hello Sir,

I am having trouble building mesa-gl with Hardknott. Apparently swrast has been removed. I tried to google-fu my way around this issue, but I can't quite figure out what needs to change in the .bbappend file to make this work.

**Comment by JeffyCN** [comment]
try something like:
https://github.com/JeffyCN/meta-rockchip/blob/master/recipes-graphics/mesa/mesa-gl_%25.bbappend

**Comment by JeffyCN** [comment]
patch uploaded:
https://github.com/JeffyCN/meta-rockchip/commit/6691c2b7c53de59280ed05ae79d90e7bd736ca7a
